// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orevbqihbxxssrnstcqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZXZicWloYnh4c3NybnN0Y3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzQ2ODQsImV4cCI6MjA2NzExMDY4NH0.9Bb1MqgUUdNGavb_lx2QJX7S-tJV5TgqgpKV-l1RHI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});